# Generated by Django 5.2.8 on 2025-11-23 08:55
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="active",
            new_name="archived",
        ),
    ]
