# Generated by Django 5.2.8 on 2025-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_invert_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
