# Generated by Django 5.2.8 on 2025-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_list_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="text",
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
